[PDF]
qbroad = 1.58868095e-02
qdamp =  1.07333909e-02
[Measurement]
keV = 59.798
[R_val]
rmin = 1
rmax = 50
rstep = 0.01
[files]
cifs = './cifs/'
out = './results/'
[Verbose]
step = true
results = true


[[param_order]]
free = ["lat", "scale"]
fix = []

[[param_order]]
free = ["cfs", "occ"] 
fix = []

[[param_order]]
free = ["delta2", "adp", "xyz"]
fix = []
